spring:
  application:
    name: evrp-backend
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  web:
    resources:
      add-mappings: false

server:
  port: 8080

cors:
  allowed-origin: http://localhost:5173

app:
  username: admin
  password: changeme

osrm:
  base-url: https://router.project-osrm.org

logging:
  level:
    hr.fer.evrp: WARN
